### ISSUE TITLE
Australia map chart does not follow the ISO 3166-2 standard codes.

### ISSUE THREAD

**Issue by spanigrahi07** [highcharts/map-collection-dist#103]
Australia map chart does not follow the `ISO 3166-2` standard codes.

Please refer to the `Wikipedia` link for standard codes, which is different from the standard codes used in `Highcharts`.

[https://en.wikipedia.org/wiki/ISO_3166-2:AU](https://en.wikipedia.org/wiki/ISO_3166-2:AU)

e.g. for `New South Wales` the `ISO 3166-2` standard code here is `AU-NSW` but the `Highcharts` support `AU-NS`. This confuses customers.

[https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/au/au-all](https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/au/au-all)

**Comment by spanigrahi07** [comment]
Hi team,
From the HB platform side, we are working on the MAP chart to support the Australia map type, due to the above problem we are not able to roll out our Australia map type change for the customers, we are on hold.

Could you please consider this a top priority and share a deadline to make fixes available, we plan to reach out to all our customers accordingly.

**Comment by KacperMadej** [comment]
Hi @spanigrahi07 
Thank you for reporting the problem.
I will look into this today.

**Comment by KacperMadej** [comment]
Here's a demo with a fixed map attached in the HTML section of the JSFiddle: https://jsfiddle.net/BlackLabel/rdwut5mb/

_Internal note:_
Codes source: [here](https://www.iso.org/obp/ui/#iso:code:3166:AU)

**Comment by spanigrahi07** [comment]
Hi @KacperMadej, Thank you for resolving this issue immediately, we really hope an ETA of new changes will be available in the map collection, so we plan to reach out to all of our customers accordingly.
Thanks

**Comment by KacperMadej** [comment]
The fix will be published in v2.0.1
