### ISSUE TITLE
world-continents: incorrect Asia data label placement

### ISSUE THREAD

**Issue by bm64** [highcharts/map-collection-dist#113]
Asia data label has incorrect placement on world-continents map.
Demo: https://jsfiddle.net/BlackLabel/L6se3q9p/
JSON: https://code.highcharts.com/mapdata/custom/world-continents.topo.json

**Comment by alparius** [comment]
bump

Any workaround?

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting the problem - this is a duplicate of https://github.com/highcharts/highcharts/issues/18004

A proper solution will require changing the base of the placement logic - switching from bbox to lon/lat based options.

**Comment by hubertkozik** [comment]
This issue is fixed.
