### ISSUE TITLE
The map of Ukraine used in Highmaps has incorrect names for cities/regions

### ISSUE THREAD

**Issue by OleksandrMalinin** [highcharts/map-collection-dist#114]
#### Product version
Highmaps https://code.highcharts.com/mapdata/countries/ua/ua-all.topo.json

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/ua/ua-all
1. Open the link above
2. Some of UA region names have incorrect names

#### Expected behaviour
1. Kyiv
3. Kyiv City
4. Odesa

#### Actual behaviour
1. Kiev
4. Kiev City
5. Odessa

**Comment by KacperMadej** [comment]
This is something that could be changed via series data like in this demo: https://jsfiddle.net/BlackLabel/jq2edmw5/

Relevant code parts:
- data with extra info for the names
```
    const data = [
        ['ua-my', 110, 'Odesa'], ['ua-ks', 11], ['ua-kc', 112, 'Kyiv City'], ['ua-zt', 13],
        ['ua-sm', 14], ['ua-dt', 15], ['ua-dp', 16], ['ua-kk', 17],
        ['ua-lh', 18], ['ua-pl', 19], ['ua-zp', 20], ['ua-sc', 21],
        ['ua-kr', 22], ['ua-ch', 23], ['ua-rv', 24], ['ua-cv', 25],
        ['ua-if', 26], ['ua-km', 27], ['ua-lv', 28], ['ua-tp', 29],
        ['ua-zk', 30], ['ua-vo', 31], ['ua-ck', 32], ['ua-kh', 33],
        ['ua-kv', 134, 'Kyiv'], ['ua-mk', 35], ['ua-vi', 36]
    ];
```
- data labels format with conditional templating:
```
            dataLabels: {
                enabled: true,
                format: '{#if point.custom.name}{point.custom.name}{else}{point.name}{/if}'
            }
```

As far as I can check those are alternative spellings. If you have an official source that could be linked claiming that the used names are wrong and should be changed please share and I could reopen the issue.

Closing as resolved.
