### ISSUE TITLE
#17521 Regrading Wrong information on Map chart

### ISSUE THREAD

**Issue by shivasaisagar18** [highcharts/map-collection-dist#117]
Hi team,

i was working on Map highcharts, while creating India map i observed its not full map of india. If you need clarification please check google. Please update it asap

![image](https://user-images.githubusercontent.com/69592387/199986434-68c34266-7d88-4fda-ab12-377ffe0fafb7.png)

![image](https://user-images.githubusercontent.com/69592387/199986405-49a28eb4-2c4c-4931-b321-5844360cd040.png)

![image](https://user-images.githubusercontent.com/69592387/199986380-029e8579-1462-48fa-9f40-5a7fdc647a4e.png)

**Comment by KacperMadej** [comment]
The map you are looking in this map collection is named India with disputed territories - https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/in/custom/in-all-disputed
