### ISSUE TITLE
Map name contain "?" character

### ISSUE THREAD

**Issue by ALevkas** [highcharts/map-collection-dist#118]
For example, you can see this on the Czech map.

<img width="729" alt="image" src="https://user-images.githubusercontent.com/47703052/216110233-c3e0d63a-acd7-4040-ae84-7eeedd121b8f.png">

in official example https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/demo/all-maps.

How do I fix this problem?
Someone may have already fixed this and have an answer.

**Comment by KacperMadej** [comment]
Hi @ALevkas 

Thank you for reporting the problem.
This is a bug with encoding in the map source file.
As a workaround, you could provide a list of correct names in the data loaded for the map. Here's a demo showing how to add it (but without the actual correct names): https://jsfiddle.net/BlackLabel/wkoy6mqd/1/

**Comment by ALevkas** [comment]
Hi @KacperMadej, thank you for the workaround. Maybe, do you know if this bug will be fixed in the near version?
