### ISSUE TITLE
Indonesia has new province, Kalimantan Utara

### ISSUE THREAD

**Issue by jon-a-nygaard** [highcharts/map-collection-dist#12]
This issue is a continuation of an issue reported in the `highcharts/highcharts` repository, please see highcharts/highcharts#7431 for full details.

**Comment by tru3d3v** [comment]
How About West Papua

**Comment by oysteinmoseng** [comment]
@tru3d3v Good point, West Papua seems to be missing too

**Comment by KacperMadej** [comment]
Isn't Irian Jaya Barat the same as West Papua?
See Paweł's map for reference: https://jsfiddle.net/0ubLdvk6/

**Comment by KacperMadej** [comment]
@tru3d3v 
woe-label property of the last shared map already has that name used, but here's the same map with edited data for the region in question:
https://jsfiddle.net/BlackLabel/bkp3s2ev/

_Internal note:_ The above change is not added to the map-collection repo.

**Comment by tru3d3v** [comment]
@KacperMadej Thank you for your help :)
