### ISSUE TITLE
Norway, no-all.geo.json has wrong title

### ISSUE THREAD

**Issue by ALevkas** [highcharts/map-collection-dist#121]
You can see example here - https://code.highcharts.com/mapdata/countries/no/no-all.geo.json

Title has "admin1"
<img width="255" alt="image" src="https://user-images.githubusercontent.com/47703052/220573795-3540e967-bd42-449d-9e09-ca7b5d723069.png">

**Comment by KacperMadej** [comment]
Thank you for reporting.

_Internal note:_
Check the script used for the title generation and look for the similar issues in all the maps.
