### ISSUE TITLE
Laos: add Xaisomboun province

### ISSUE THREAD

**Issue by jon-a-nygaard** [highcharts/map-collection-dist#13]
This issue is a continuation of an issue reported in the `highcharts/highcharts` repository, please see highcharts/highcharts#7442 for full details.

**Comment by KacperMadej** [comment]
_Internal note:_
Overpass query for the OSM source:
```c
area["ISO3166-1"="LA"]->.a;
(
    rel(area.a)["admin_level"="4"];
);
out body;
>;
out skel qt;
```

TBD: legacy map properties copied into the new source
