### ISSUE TITLE
New map: United Kingdom with Crown Dependencies

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/map-collection-dist#130]
The original feature request:

> Islands Guernsey, Jersey and Isle of man are absent on the map and they don’t exist in the list of UK regions

**Comment by centenico** [comment]
@KacperMadej Hi, did you add the Jersey & the other island to the highcharts map? If so, may I ask you in which map and if you could link it to me? Thanks a lot!

**Comment by hubertkozik** [comment]
@centenico You can find all of the maps available in the Highcharts Map Collection here: https://code.highcharts.com/mapdata/

The one, which includes changes with Guernsey, Jersey and Isle of Man is United Kingdom countries with the Crown Dependencies: https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/gb/custom/uk-countries-and-crown-dep
