### ISSUE TITLE
New map: City-level China Map 

### ISSUE THREAD

**Issue by lyiabv** [highcharts/map-collection-dist#131]
There is only province/state level map data in highcharts. It would be really helpful if there were city-level maps.

Thank you!

**Comment by KacperMadej** [comment]
Hi @lyiabv 

Thank you for suggesting the enhancement.

Do you mean a map of a city with division into neighborhoods?
Or higher level of admin divisions? Like Chinese provinces with division into prefectures?

There's an option to [create custom maps](https://www.highcharts.com/docs/maps/create-custom-maps) or use [TWM](https://www.highcharts.com/docs/maps/tiledwebmap) as a background map - [a short blog article with an example for China](https://www.highcharts.com/blog/tutorials/map-highcharts-openstreetmap/).

**Comment by lyiabv** [comment]
Hi @KacperMadej ,

Thank you for the reply.
I mean a city level density map of China which can be used for tracking sales of each city. 

I took a look at how to customize a map option, but it is way too difficult for us. TT

Would it be possible to have similar map for China? This is a demo I found on highcharts.
![image](https://github.com/highcharts/map-collection-dist/assets/109444604/9062f719-76f0-4907-921b-8979084452bd)

**Comment by KacperMadej** [comment]
At this moment we don't have such a map available in our Map Collection. However, from your description, it seems that you might solve your problem with a point-based data (appoint series type) and a background map for context - TWM series type. More info could be found here: https://www.highcharts.com/docs/maps/tiledwebmap

If you would like for this issue to remain open as a feature request for a map, please provide more technical details for the map you are requesting - like what administration division should it represent; potential source (if you have any); or anything that could help not only with creating the map but also with validating that it will be correct.

**Comment by KacperMadej** [comment]
Due to the lack of reply I will be closing this issue as an answered question about adding points to a map.
