### ISSUE TITLE
New regions in Norway from 2024

### ISSUE THREAD

**Issue by audunigesund** [highcharts/map-collection-dist#133]
There will be new regions in Norway. 
Fylker (Counties): https://www.regjeringen.no/no/tema/kommuner-og-regioner/kommunestruktur/fylkesinndelingen-fra-2024/id2922222/
Kommuner (Municipalities) with new numbers: https://www.regjeringen.no/no/tema/kommuner-og-regioner/kommunestruktur/nye-kommune-og-fylkesnummer-fra-1.-januar-2024/id2924701/

**Comment by KacperMadej** [comment]
Thank you for reporting the problem.

_Internal note:_
OSM is not yet updated. The changes don't look like simple changes that could be done manually so it might be better to wait for OSM or reach out to people responsible for the Norway map in OSM for more info.

**Comment by elisabeth-voss** [comment]
Are there any update on this issue?

**Comment by hubertkozik** [comment]
I've added this issue to an internal discussion where we decide on the future of this ticket.

**Comment by Trude** [comment]
Any updates on this? Is there anywhere else I can follow to see if there is any progress on this?

**Comment by hubertkozik** [comment]
Hi @Trude!
The ticket is prioritized in our Backlog, we will add new regions to the Norway map soon. When the work starts, you will see notifications here, in this GitHub ticket.

**Comment by elisabeth-voss** [comment]
Hello, do you know when this work will start?

**Comment by hubertkozik** [comment]
Hi @elisabeth-voss! The work is in progress, currently on our private repository. We've got some maps, but it still needs some adjustments. Do you need any map as a workaround? I can prepare some for you before we release the new version.

**Comment by ingrskar** [comment]
Thank you for the update! Could you provide an approximate timeline for when the adjustments might be completed? Additionally, if it's possible, I would greatly appreciate having access to the workaround maps in the meantime.

**Comment by hubertkozik** [comment]
@ingrskar Here's the demo with Norway TopoJSON map with new regions: https://jsfiddle.net/BlackLabel/38v7Lwbr/

**Comment by ingrskar** [comment]
Thank you for the workaround. Are you able to share the GeoJSON as well? Specifically, I'm interested in both the GeoJSON for counties and the one for municipalities, if available.

**Comment by Trude** [comment]
Hi! Is there a release coming soon with a fix for the new regions (municipalities and counties)? Since the issue was closed last week?
