### ISSUE TITLE
Use secure https in the demos' subtitle.

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/map-collection-dist#134]
Change from
```js
subtitle: {
            text: 'Source map: <a href="http://code.highcharts.com/mapdata/custom/africa.topo.json">Africa</a>'
        },
```

to the URL starting with `https`.

**Comment by eriksoeb** [comment]
Thanks, this is Probably my typeoff 😎📈Erik13. nov. 2023 kl. 16:55 skrev Kacper Madej ***@***.***>:﻿
Change from
subtitle: {
            text: 'Source map: <a href="http://code.highcharts.com/mapdata/custom/africa.topo.json">Africa</a>'
        },
to the URL starting with https.

**Comment by KacperMadej** [comment]
Hi @eriksoeb 

To be honest I have no clue what you mean. How may I help?
