### ISSUE TITLE
Update Norwegian Map with Regional Changes in 2024

### ISSUE THREAD

**Issue by elisabeth-voss** [highcharts/map-collection-dist#137]
At 1th of January 2024, the Norwegiain Regions will be updated. When will the Norwegian maps be updated in Highcharts map collection?

**Comment by KacperMadej** [comment]
Hi @elisabeth-voss 

Thank you for reporting the problem. Could you provide more info or check if this is not a duplicate of https://github.com/highcharts/map-collection-dist/issues/133 ?

**Comment by elisabeth-voss** [comment]
Hello @KacperMadej 
Yes, this is the same case. What is the status on this?
