### ISSUE TITLE
Displaying HongKong as a Country in Asia Map

### ISSUE THREAD

**Issue by NtrustInfotech** [highcharts/map-collection-dist#145]
We are new to high charts and we have already developed map charts to display the number of leases for every Continent Further it can drill down to the country level and then state level. 

1. Asia map displaying HongKong as a country in our previous version but we are unable to replicate here
![Hongkong as a country](https://github.com/highcharts/map-collection-dist/assets/166793988/9d059e79-38a5-4494-9031-8d5fd73fc0d3)

2. Hongkong states in our previous version and we are not able to identify this
![Hongkong city map request](https://github.com/highcharts/map-collection-dist/assets/166793988/6465823a-e6de-4923-a9e7-885bcf545a2f)

We are not able to achieve this in highcharts. 
Please let us know how to proceed on this.

**Comment by KacperMadej** [comment]
Hi @NtrustInfotech 

For technical support please contact us using one of the available for you channels: https://www.highcharts.com/blog/support/

Available maps that include Hong Kong are listed in [the Map Collection main CDN page](https://code.highcharts.com/mapdata/) and include: "China with Hong Kong and Macau" and "China with Hong Kong, Macau, and Taiwan". Using TopoJSON map file format you can combine multiple different maps to create e.g. Asia region with any country or part of the world.

There is no Hong Kong map available in the Map Collection at this moment so you could use such a map if added as a custom map as documented [here](https://www.highcharts.com/docs/maps/create-custom-maps) or [here](https://www.highcharts.com/docs/maps/custom-geojson-maps).

I can change this issue into a feature request for the Hong Kong map that should be added to the Map Collection or close this as an answered technical support question. Please let me know which option is better for you and if you have any more questions please ask.

**Comment by KacperMadej** [comment]
Closing as an answered technical support question.
