### ISSUE TITLE
Update county boundaries for Connecticut, USA

### ISSUE THREAD

**Issue by jedrzejruta** [highcharts/map-collection-dist#146]
The county boundaries of Connecticut, USA have been recently updated and are reflected on the [US Census TIGER](https://www2.census.gov/geo/tiger/TIGER2023/COUNTY/) files as well as on the [Connecticut Geodata Portal](https://geodata.ct.gov/datasets/743ea4808b85469d8d9f7c5e6b661ee8/explore?location=41.494300%2C-72.586199%2C8.83)

**Comment by Unidraga** [comment]
Connecticut updated their county boundaries recently. More information [here](https://geodata.ct.gov/datasets/743ea4808b85469d8d9f7c5e6b661ee8/explore?location=41.494300%2C-72.586199%2C8.83)

And the new County Map is released on [US Census TIGER](https://www2.census.gov/geo/tiger/TIGER2023/COUNTY/)

I'm looking for the Connecticut County Map on highcharts [map collection](https://code.highcharts.com/mapdata/countries/us/us-ct-all.geo.json) to be updated with the latest version

**Comment by KacperMadej** [comment]
_Internal note:_
OSM:
```
area["ISO3166-2"="US-CT"]->.a;
(
    rel(area.a)["admin_level"="6"];
);
out body;
>;
out skel qt;
```

**Comment by KacperMadej** [comment]
Pre-release map update preview for testing:
[us-ct-all.topo.json](https://github.com/highcharts/map-collection-dist/files/15418511/us-ct-all.topo.json)
[us-ct-all.geo.json](https://github.com/highcharts/map-collection-dist/files/15418510/us-ct-all.geo.json)
![us-ct-all](https://github.com/highcharts/map-collection-dist/assets/8960408/e5f67187-d8ce-41e9-b330-05339ec15129)

**Comment by Unidraga** [comment]
Thanks KacperMadej! 
Map looks good! Is there a timeline on when it will be released onto map collection?

**Comment by KacperMadej** [comment]
@Unidraga 
Thank you for checking out the map.
The release is planned for this week.

**Comment by Unidraga** [comment]
@KacperMadej thanks for the great work! Looking forward to the release!

**Comment by ViktorKoziyatko** [comment]
Hi @KacperMadej. 
Is it possible to get an old version of the topo.json file for Connecticut? The new boundary update is great, but I still need to use the old one for the time being. Just wondering if it's possible to get it as a file, link, or in some other form.

Thank you!

**Comment by hubertkozik** [comment]
Hi @ViktorKoziyatko! Of course, you can find old maps in "HISTORICAL" Sections: https://code.highcharts.com/mapdata/

Old Connecticut map is under "HISTORICAL: OTHER" section: https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/historical/countries/us-2023/us-ct-all-2023

**Comment by ViktorKoziyatko** [comment]
@hubertkozik 
Oh man, I should have kept my eyes more open. I didn't even think of looking at the bottom of that page. Thank you very much!
