### ISSUE TITLE
Mismatched key for china's mapdata

### ISSUE THREAD

**Issue by BipinKrishna-Draup** [highcharts/map-collection-dist#151]
#### Expected behaviour

For this Mapdata URL: https://code.highcharts.com/mapdata/countries/cn/cn-all.js

I should be getting response with key `countries/cn/cn-all`

#### Actual behaviour

but i am actually getting response with the key `countries/cn/custom/cn-all`

```js
Highcharts.maps["countries/cn/custom/cn-all"] = {"title":"China","version":"2.3.0"...
```

**Comment by hubertkozik** [comment]
Thank you for reporting the issue. Indeed, the key is JS file should be `countries/cn/cn-all`.
