### ISSUE TITLE
Norwegian charts are stretched in 2024 version

### ISSUE THREAD

**Issue by c0d3x** [highcharts/map-collection-dist#154]
When using the charts from 2024 both region and muncipalities, the map is stretched compared to the 2019 and 2020 versions.

**2024 from OpenStreetMap**
![image](https://github.com/user-attachments/assets/e96831eb-6b9d-43b2-b2c1-24c3ff3714fd)

**Earlier version from Natural Earth:**
![image](https://github.com/user-attachments/assets/fe9651f2-4179-4c2b-a89d-210b6f1ad653)

**Earlier version from Kartverket:**
![image](https://github.com/user-attachments/assets/25b46e68-67fb-4bd5-ac43-70ab28f9d948)

**Comment by KacperMadej** [comment]
Hi @c0d3x 
Could you add a live demo (e.g. in JSFiddle)?
I don't see this on the official demo: https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/no/no-all
This should be possible to resolve by setting a [map projection](https://api.highcharts.com/highmaps/mapView.projection).

**Comment by c0d3x** [comment]
> Hi @c0d3x Could you add a live demo (e.g. in JSFiddle)? I don't see this on the official demo: https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/no/no-all This should be possible to resolve by setting a [map projection](https://api.highcharts.com/highmaps/mapView.projection).

I will make a JSFiddle tomorrow if I cannot solve it with map projection.
By chanse do you know which projection I am looking for to make it look like the former maps I have?

**Comment by c0d3x** [comment]
Actually if you change your JSfiddle to use geo instead of topo, you get the stretched effect:
https://jsfiddle.net/zya6m0h8/

**Comment by KacperMadej** [comment]
Yes, here's the solution.
Demo: https://jsfiddle.net/BlackLabel/Lojg5h1t/
Relevant options:
```
        mapView: {
        	projection: {
                name: 'LambertConformalConic',
                parallels: [
                    57.993,
                    71.165
                ],
                rotation: [
                    -17.854971943887776
                ]
            }
        },
```

Is this working for you? @c0d3x

**Comment by c0d3x** [comment]
> Yes, here's the solution. Demo: https://jsfiddle.net/BlackLabel/Lojg5h1t/ Relevant options:
> 
> ```
>         mapView: {
>         	projection: {
>                 name: 'LambertConformalConic',
>                 parallels: [
>                     57.993,
>                     71.165
>                 ],
>                 rotation: [
>                     -17.854971943887776
>                 ]
>             }
>         },
> ```
> 
> Is this working for you? @c0d3x

Did not work, you can try the fiddle here, if you can make it work:
https://jsfiddle.net/r0eqbgcd/10/

**Comment by c0d3x** [comment]
> mapView is a top level option - should be placed not in the chart options, but next to it. https://jsfiddle.net/BlackLabel/oz8hr1j9/ Your `fitToGeometry` option is wrong and doesn't work. It should be easier to use a simple geometry of Norway from a word map or define a few points that will limit the view (more: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/mapview/fittogeometry)
> 
> This looks like a problem with the chart/map configuration, and not a Map Collection issue, (so I will close the issue, but we can continue the conversation). For technical support please use one of our available channels - https://www.highcharts.com/support/

Looks like it works in your fiddle, maybe there is a different method since I am using the react library?
https://github.com/highcharts/highcharts-react

![image](https://github.com/user-attachments/assets/81e791f4-a155-4b08-9e40-fdc76f788db2)

Map dissapeared:
![image](https://github.com/user-attachments/assets/74d76a2f-609f-4ab4-a370-12e5b55844cd)

**Comment by c0d3x** [comment]
The culprit was the padding: [10], also when I added your **LambertConformalConic** the 2024 map works awesome.
But the older maps stopped working:
![image](https://github.com/user-attachments/assets/90e5b1b9-605b-4fc6-beb1-5128b456f287)
