### ISSUE TITLE
In newly contributed India map with Telangana, the hc-a2 code for Andhra Pradesh and Arunachal Pradesh is same. This will result in a conflict when try to plot data from Json

### ISSUE THREAD

**Issue by jon-a-nygaard** [highcharts/map-collection-dist#27]
This issue is a continuation of an issue reported in the `highcharts/highcharts` repository, please see highcharts/highcharts#9236 for full details.

**Comment by KacperMadej** [comment]
Duplicate of https://github.com/highcharts/map-collection-dist/issues/46#issuecomment-847008997
(link to a workaround)
