### ISSUE TITLE
How to import all maps

### ISSUE THREAD

**Issue by pavitranrambo** [highcharts/map-collection-dist#31]
Since there is not a way to dynamically import maps individually, is there a way to import all maps say in the countries folder?

**Comment by KacperMadej** [comment]
Hi @pavitranrambo 

After you will install the NPM module all maps will be downloaded into the related directory in node_modules. Single map usage is described in docs: https://github.com/highcharts/map-collection-dist#install-from-npm

**Comment by pavitranrambo** [comment]
Hello KacperMadej,

I have done what you have described. 
However, my problem is I want the user to be able to choose what country they want during runtime. 

Currently, I do not know a way to import specific geojson files through variables or conditional statements.

So the only other way I can think of is to import all the geojson files into the script I am working on all at once. Is there any way to do that?

**Comment by KacperMadej** [comment]
You could load the map files dynamically. Here's a demo loading maps from CDN (code.highcharts.com/mapdata/) - https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/demo/map-drilldown/
Another example can be found here: https://www.highcharts.com/maps/demo/all-maps

**Comment by fatimasajjad** [comment]
I follow the demo/all-maps link in angular typescript project but I get exception at Highcharts.geojson and also Highcharts.mapDataIndex is undefined.

Please answer the following issue:

https://github.com/highcharts/highcharts/issues/10069

**Comment by KacperMadej** [comment]
Let's continue on Highcharts repo issue to avoid duplication

**Comment by KacperMadej** [comment]
@fatimasajjad case is moved to Highcharts main repo

The original issue is answered and will now be closed due to inactivity (IMHO it's resolved).
