### ISSUE TITLE
Individual maps of Norway counties should also be merged just like on the main map

### ISSUE THREAD

**Issue by Denyllon** [highcharts/map-collection-dist#33]
There are still 19 individual maps of Norway counties, but the Nord-Trøndelag and Sør-Trøndelag regions were merged into one Trøndelag on the main map, so the maps of those regions should also be merged into one.

Data source: https://en.wikipedia.org/wiki/Counties_of_Norway
Related issue: https://github.com/highcharts/highcharts/issues/8199

**Comment by KacperMadej** [comment]
Working correctly since map collection v1.1.3 (https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/no/no-all)
