### ISSUE TITLE
Swaziland was renamed to Eswatini

### ISSUE THREAD

**Issue by GediminasN** [highcharts/map-collection-dist#42]
Eswatini (Swazi: Umbuso weSwatini) and also known as Swaziland (officially renamed in 2018).
https://en.wikipedia.org/wiki/Eswatini

**Comment by KacperMadej** [comment]
Hi @GediminasN 

Thank you for reporting the problem.

As a workaround, it is possible to alter the used map to include the needed change.

_Internal note:_
World map change required.

**Comment by danday74** [comment]
I got around this using npm patch-package but would prefer a fix from you guys - thx
