### ISSUE TITLE
Norway administrative change into 11 states by 2020

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/map-collection-dist#43]
More info: https://www.regjeringen.no/no/tema/kommuner-og-regioner/regionreform/regionreform/nye-fylker/id2548426/

Update admin2 maps for Norways as well.

**Comment by oysteinmoseng** [comment]
Note the changes on admin2 level as well: https://www.regjeringen.no/no/tema/kommuner-og-regioner/kommunereform/id751048/.

There may be changes beyond merging, not sure about details, so would consider updating with fresh source.

**Comment by oysteinmoseng** [comment]
Sources counties (adm1): https://kartkatalog.geonorge.no/metadata/f01922f5-bc7b-489f-918c-ca0f789c0dfa
Sources municipalities (adm2): https://kartkatalog.geonorge.no/metadata/f015cd24-a14b-42f3-b695-848cb88d9657

**Comment by oysteinmoseng** [comment]
Should also add county/municipality numbers if not present in source data. (Fylkesnummer/kommunenummer)

**Comment by KacperMadej** [comment]
There is a problem with the map sources. All the maps are about zones for each district and are not showing the shape of the land at the sea border. The lack of details is very noticeable.

![nor_overlay](https://user-images.githubusercontent.com/8960408/69978749-46936d80-152d-11ea-914e-8769114c2e90.jpg)

I have this shape from SOSI format (converted into QGIS usable .shp). Other layers are just lines around the zones. Maybe there is another format that could be downloaded and used in QGIS from those web sites that have more details. The web sites are in Norwegian and I can only hope that Google is translating the pages correctly. It would be nice if someone that speaks (or at least reads) Norwegian could help with this. @oysteinmoseng

**Comment by KacperMadej** [comment]
In the meantime I will try to adjust the existing map sources with the 2020 changes - the changes don't look that drastic.

**Comment by oysteinmoseng** [comment]
I took a look at the source page, but doesn't look like speaking Norwegian is of much help here... 🤔

What we have done with some other datasets is generate the admin 1 data from the admin 2 (kommune) dataset. There should be a `join_by_fields` function in `toolbox.py` that does this for you, if you just configure it to use the correct data field. Maybe that is easier than hand-editing the lines.

**Comment by hakonviervoll** [comment]
Any update on this?

**Comment by KacperMadej** [comment]
@hakonviervoll 
The maps are ready and will be a part of the next map collection release - ETA by the end of the current week.
