### ISSUE TITLE
Add `;` add the end of JS files

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/map-collection-dist#45]
Sometimes when files have loaded the lack of ending `;` is causing some problems.

This was resolved previously like in here: https://github.com/highcharts/node-export-server/commit/2d07efcab1ab37660228736a5e6a3196f64be617

Related closed PR for more info: https://github.com/highcharts/map-collection-dist/pull/44

**Comment by madepiet** [comment]
Closed with: https://github.com/highcharts/map-collection/pull/11
