### ISSUE TITLE
Turkey: symbol coding

### ISSUE THREAD

**Issue by raf18seb** [highcharts/map-collection-dist#48]
Take a look at this map: https://code.highcharts.com/mapdata/countries/tr/tr-all.js
There are many properties with uncoded values:
![tr](https://user-images.githubusercontent.com/23310742/70729290-3769a800-1d03-11ea-9c97-69b92464327d.PNG)

I discovered this when fixing issue with dataLabels, see: https://github.com/highcharts/map-collection-dist/issues/14
I manually changed only **"name"** and **"woe-name"** properties so the dataLabels could be displayed correctly now, but we need to consider what to do with the rest of properties.

**Comment by KacperMadej** [comment]
It is all fine when using the map - https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/tr/tr-all

Closing as not a problem - might reopen in case of issues in sources.
