### ISSUE TITLE
Mapdata for Malawi is incorrect

### ISSUE THREAD

**Issue by MaluwaLMK** [highcharts/map-collection-dist#52]
#### Expected behaviour
The mapdata provided here https://code.highcharts.com/mapdata/countries/mw/mw-all.geo.json has an error. For `"woe-id": "20070125"`, the `"name"` should be `"Karonga"` and `"woe-name": "Karonga"`. This will result in correct labels for `Karonga` and `Chitipa` on the map.

#### Live demo with steps to reproduce

Hover on the two northernmost districts. The one on the west is Chitipa and on the east is Karonga.
https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/mw/mw-all

**Comment by KacperMadej** [comment]
Hi @MaluwaLMK 

Thank you for reporting the problem.

_Internal note:_
There is an error in the map - the name of the region should be changed.
