### ISSUE TITLE
Norway: counties not up-to-date after 1. jan 2020

### ISSUE THREAD

**Issue by evensrii** [highcharts/map-collection-dist#54]
Dear Highcharts,

You have done a great job updating the Norwegian county maps for the "county reform". Nevertheless, many changes to the muncipality borders within most of the counties took effect 1. jan 2020, and these changes are not incorporated in the Highcharts maps of the new Norwegian counties.

The official map source is: https://www.geonorge.no/en/
I believe this is the up-to-date and correct county map: https://kartkatalog.geonorge.no/metadata/administrative-units-counties/6093c8a8-fa80-11e6-bc64-92361f002671

We would highly appreciate if Highcharts took the time to update the Norwegian county maps!

Kind regards,

Even S. Riiser

**Comment by KacperMadej** [comment]
2020 reform was implemented in the Norwegian maps - available since the map collection v1.1.3
Closing as resolved - not sure why this was not closed before. Feel free to leave a comment and we could reopen.
