### ISSUE TITLE
Adding state Ladakh to the map of india.

### ISSUE THREAD

**Issue by vdamodhar123** [highcharts/map-collection-dist#57]
Hi,

"Ladakh" state is not added in India with a disputed territories map,

So please let us know when it will be added in India Map!

**Comment by KacperMadej** [comment]
Hi @vdamodhar123 

Thank you for reporting about the problem.

More info: https://en.wikipedia.org/wiki/Jammu_and_Kashmir_Reorganisation_Act,_2019

Looks like a duplicate of https://github.com/highcharts/map-collection-dist/issues/46

Could you confirm that those are the same problems? @vdamodhar123

**Comment by vdamodhar123** [comment]
yes these are the same problem
