### ISSUE TITLE
Denmark: Region, spelling mistake?

### ISSUE THREAD

**Issue by svjakobs** [highcharts/map-collection-dist#66]
The region Sjælland is misspelled as Sjaælland in the Denmark map.

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting the problem.

_Internal note:_
Typo in the map data.
Unable to manually change the map due to encoding - losing special characters while editing/viewing the map file content in a web browser.

**Comment by KacperMadej** [comment]
Workaround: https://jsfiddle.net/BlackLabel/0cuzwLsa/
