### ISSUE TITLE
World map supports with India-Disputed Territories

### ISSUE THREAD

**Issue by Shruthi2125** [highcharts/map-collection-dist#68]
Hi Team,
   We wanted to use **World map with disputed India Territories** which is currently not available in Highmaps colllection.
The users are mainly concerned about Jammu and Kashmir in World map which is not shown in the World geo jsons.
Kindly let me know on how to achieve this.

**Comment by PrateekGoyal18** [comment]
Use Amcharts 4, it has this feature. I also used that only.

**Comment by Shruthi2125** [comment]
We are recommended to use highcharts only.

**Comment by PrateekGoyal18** [comment]
Then you got to wait for their technical team to fix this issue. 
https://github.com/highcharts/map-collection-dist/issues/46#issuecomment-631096164

**Comment by KacperMadej** [comment]
Hi,
Thank you for contacting us about the problem. This is already reported in another issue, so this one will be closed as a duplicate. Please continue on the main issue in case you have any comments on the topic.

**Comment by Shruthi2125** [comment]
@KacperMadej :What is the original issue number?
Is this problem answered?

**Comment by PrateekGoyal18** [comment]
#46
