### ISSUE TITLE
Montenegro: a gap in the map

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/map-collection-dist#82]
![mntngr](https://user-images.githubusercontent.com/8960408/107347003-a7212180-6ac5-11eb-8f63-9a3b0a8afa85.jpg)

**Comment by hubertkozik** [comment]
_Internal note:_
Overpass query:
area["ISO3166-1"="ME"]->.me;
(
    rel(area.me)["admin_level"="6"];
);
out body;
>;
out skel qt;
