### ISSUE TITLE
missing countries from woldmap

### ISSUE THREAD

**Issue by sirdawidd** [highcharts/map-collection-dist#83]
So far I see that some of countries from world map are missing:

Aland Islands
Anguilla
Aruba
British Virgin Islands 
Cayman Islands
Cabo Verde
Cocos (Keeling) Islands
Comoros
Equatorial Guinea
Falkland Islands (Malvinas)
French Southern Territories
Ghana
Gibraltar
Guadeloupe
Guernsey
Guyana
Guinea-Bissau
Isle of Man
Heard And Mc Donald Islands
Hong Kong SAR, China
Heard Island and McDonald Islands
Mauritius
Martinique
Montserrat
Niue
St. Lucia
Saint Martin
Saint Pierre and Miquelon
St. Vincent and the Grenadines
Seychelles
Timor-Leste
Turks and Caicos Islands
Wallis And Futuna Islands

**Comment by KacperMadej** [comment]
Hi @sirdawidd 

Thank you for reporting the problem.

Is this list about any particular world map? Because Ghana and Mauritius are not missing here - https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/custom/world (World, Miller projection, medium resolution) - those two are just an example, I have not checked all of the reported missing countries.

Not all of those are countries and most of them are not big enough to show on a medium resolution world map.
Is a map with countries so small that they won't be visible anyway ok for you? or maybe you need a different solution that you could describe?

The list is not complete (doesn't cover some of the countries from this issue: https://github.com/highcharts/map-collection-dist/issues/71). Could add more info about the source of your list?

**Comment by sirdawidd** [comment]
Hi,
I was mislead about Ghana and Mauritius  because in highcharts is continent called Ocean or something like that, while it should be according wikipedia Africa hihttps://en.wikipedia.org/wiki/Mauritius (but this is a minor issue)
And regarding Countries like Gibraltar they are displaying now as UK. So you could just adjust the coordinates.
Regarding the size of some islands for example Isle of Man is really huge to compare the other islands which exists now.

However as I'm using highcharts in commercial project, I had to have all countries, for that I overloaded worldmap. I also detected small problem, For example, If I wanted to overload Giblartar which already have defined coordinates as UK (in the worldmap), and I wanted to show only Gibraltar in my map, I had to display UK, and Gibraltar otherwise Gibraltar was not visible on the map. I think there is a problem with displaying order of labels. For that purpose I had to define my custom UK coordinates, without Gibraltar coordinates.

```
export const mapWorldData = {
    ...mapDataWorld,
    ...{
      features: [
        ...mapDataWorld.features,
        {
          type: "Feature",
          id: "Gibraltar",
          properties: {
            "hc-group": "admin0",
            "hc-key": "gi",
            "hc-a2": "GI",
            name: "Gibraltar",
            labelrank: "99",
            subregion: "South Europe",
            "iso-a3": "GIB",
            "iso-a2": "GI",
            continent: "Europe",
          },
          geometry: {
            type: "Polygon",
            coordinates: [
              [
                [4046, 7594],
                [4045, 7593],
                [4045, 7594],
                [4046, 7594],
              ],
            ],
          },
        },
  };
```

**Comment by KacperMadej** [comment]
If you could share a live demo with the edited map and let me know about the problems I believe we could resolve those issues. In case you are not able to post online the data you might contact technical support via e-mail - https://www.highcharts.com/blog/support/

This will be rather a tedious task as we have to go with every country/region one by one.

Most of the listed regions are not on our world map as those are not countries. However, discussing if a region is a country or not is not the point of this issue - it doesn't change anything from a technical point of view, we just need to add some additional features to the map and possibly edit the existing ones.

> Regarding the size of some islands for example Isle of Man is really huge to compare the other islands which exists now.

If a region that you would like to be added to the world map is big enough to be easily rendered then there is no problem. Cocos (Keeling) Islands are small and scattered islands and those will have to be approximated to something for a small resolution map - a small triangle in the middle should work ok. Unless you have other ideas?

We have multiple world maps available (with different levels of details and different projections) - which one are you using? Maybe I am not using the same map as you are but Ghana's continent is Africa in our world map (same link as in my previous comment). As for Mauritius it has `"continent":"Seven seas (open ocean)"` - I am unable to find the info about it being in Africa on the link you have provided.

**Comment by KacperMadej** [comment]
Closing due to inactivty
