### ISSUE TITLE
Norway map: 3020 is for Norde Follo

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/map-collection-dist#94]
More info in https://github.com/highcharts/map-collection-dist/issues/91#issuecomment-979323746

**Comment by KacperMadej** [comment]
Let's extend this ticket to check if all codes in Norway maps are correct - admin1 and admin2. If this would be better to create a new issue then please do @raf18seb

**Comment by raf18seb** [comment]
Here is the ticket https://github.com/highcharts/map-collection-dist/issues/95
